samples:
  - species: Rhizophora mangle
    sra:
      - id: SRR18449640
        reference: NC_042819.1
        reference_type: chloroplast
        mapper: bowtie2
  - species: Manihot esculenta
    sra:
      - id: SRR23479997
        reference: NC_045136.1
        reference_type: chloroplast
        mapper: bowtie2
  - species: Avicennia schaueriana
    sra:
      - id: SRR7404997
        reference: NC_063736.1
        reference_type: chloroplast
        mapper: bowtie2
  - species: Bufo gargarizans
    sra:
      - id: SRR34186068
        reference: NC_008410.1
        reference_type: mitochondrial
        mapper: bowtie2
