name: snakegard
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - snakemake
  - singularity
  - wget
  - unzip
  - entrez-direct
  - sra-tools
  - fastqc
  - fastp
  - multiqc