name: snakegard
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - snakemake=9.8.0
  - singularity=3.8.7
  - wget=1.21.4
  - unzip=6.0
  - entrez-direct=24.0
  - sra-tools=3.2.1
  - fastqc=0.12.1
  - fastp=1.0.1
  - multiqc=1.30
  - quast=5.3.0